
# Site settings
title: Portfólio Rodrigo Silva Rocha
description: "Bem-vindo ao meu portfólio pessoal, onde compartilho meus projetos e experiências."
baseurl: "" # Base URL do seu site, se estiver em uma subpasta
url: "http://seu-domínio.com" # URL do seu site

# Author settings
author:
  name: "Rodrigo Silva Rocha"



# Build settings
markdown: kramdown # Usar Kramdown como processador de Markdown
theme: minima # Tema padrão do Jekyll

# Plugins (se necessário)
plugins:
  - jekyll-feed # Para gerar um feed RSS
  - jekyll-seo-tag # Para SEO otimizado

# Permalink settings
permalink: pretty # Usar permalinks bonitos




collections:
  projects:
    output: true

#   - vendor/ruby/